画板:
  画板宽度: 1600
  画板高度: 1024
  画板背景色: '#555555'

图例参数:
  图例列间距: 4
  图例项纵间距: 2
  图例字体大小: 14
  图例项高度: 20
  图例项宽度: 100
  每列图例项数量: 10
  图例起始X坐标: 20
  图例起始Y坐标: 20
  图例图层: 10
  #图例项圆角: 3  # 图例项圆角 已弃用 使用功能组圆角属性

标签参数:
  标签高度: 15
  标签间距: 5
  标签图层: 4
  标签宽度比文本宽多少: 5

芯片主体参数:
  芯片主体图层: 3
  芯片文本图层: 5
  芯片主体边框宽度: 5
  芯片主体颜色: '#000000'
  芯片主体圆角半径: 10
  芯片标题字体: Impact # 芯片标题字体 厂商名
  芯片标题字体大小: 26
  芯片名称字体: KaiTi # 芯片名称字体 芯片名
  芯片名称字体大小: 22
  芯片信息字体: KaiTi # 芯片信息字体 封装信息
  芯片信息字体大小: 12
  1脚标志图层: 6 # 1脚标志图层
  1脚标志颜色: '#000000' # 1脚标志颜色
  1脚标志边框直径: 1 # 1脚标志边框直径
  1脚标志边框颜色: '#000000' # 1脚标志边框颜色
  PIN1脚标志位置X: 15 # PIN1脚标志距离芯片主体的距离
  PIN1脚标志位置Y: 15 # PIN1脚标志距离芯片主体的距离
  QFN1脚标志位置X: 10 # QFN1脚标志距离芯片主体的距离
  QFN1脚标志位置Y: 10 # QFN1脚标志距离芯片主体的距离

焊盘:
  PID中心焊盘:
    PID_中心焊焊盘颜色: '#cccccc'
    PID_中心焊盘X偏移: 0
    PID_中心焊盘Y偏移: 0
    PID_中心焊盘图层: 1
    PID_中心焊盘圆角: 2
    PID_中心焊盘宽度: 35
    PID_中心焊盘高度: 60
    PID_中心焊边线宽度: 0
    PID_中心焊边线颜色: '#ffffff'
  PID焊盘:
    PID标签间距: 6 # 标签与标签之间的间距
    PID引脚与标签间距: 10 # 引脚与标签之间的间距
    PID焊盘编号字体: Arial
    PID焊盘编号字体大小: 8
    PID焊盘高度: 10 # 焊盘高度
    PID焊盘宽度: 20 # 焊盘宽度
    PID焊盘间距: 20 # 焊盘间距
    PID_焊盘图层: 2 # 焊盘图层
    PID_焊盘圆角: 2 # 焊盘圆角
    PID_焊盘编号字体颜色: '#000000' # 焊盘编号字体颜色
    PID_焊盘颜色: '#cccccc'
    PID_边线宽度: 1 # 焊盘边线宽度
    PID_边线颜色: '#000000' # 焊盘边线颜色
  QFP中心焊盘:
    QFP_中心焊焊盘颜色: '#cccccc'
    QFP_中心焊盘X偏移: 0
    QFP_中心焊盘Y偏移: 0
    QFP_中心焊盘图层: 1
    QFP_中心焊盘圆角: 2
    QFP_中心焊盘宽度: 100%
    QFP_中心焊盘高度: 100%
    QFP_中心焊边线宽度: 0
    QFP_中心焊边线颜色: '#ffffff'
  QFP焊盘:
    QFP标签间距: 10 # 标签间距与标签之间的间距
    QFP引脚与标签间距: 100 # 引脚与标签之间的间距
    QFP焊盘编号字体: Arial
    QFP焊盘编号字体大小: 8
    QFP焊盘高度: 10 # 焊盘高度
    QFP焊盘宽度: 20 # 焊盘宽度
    QFP焊盘间距: 20 # 焊盘间距
    QFP_焊盘图层: 2 # 焊盘图层
    QFP_焊盘圆角: 2 # 焊盘圆角
    QFP_焊盘编号字体颜色: '#000000' # 焊盘编号字体颜色
    QFP_焊盘颜色: '#cccccc'
    QFP_边线宽度: 1 # 焊盘边线宽度
    QFP_边线颜色: '#000000' # 焊盘边线颜色
  QFN中心焊盘:
    QFN_中心焊焊盘颜色: '#cccccc'
    QFN_中心焊盘X偏移: 0
    QFN_中心焊盘Y偏移: 0
    QFN_中心焊盘图层: 1
    QFN_中心焊盘圆角: 6
    QFN_中心焊盘宽度: 100%
    QFN_中心焊盘高度: 100%
    QFN_中心焊边线宽度: 0
    QFN_中心焊边线颜色: '#ffffff'
  QFN焊盘:
    QFN标签间距: 6 #标签与标签之间的间距
    QFN引脚与标签间距: 10 #引脚与标签之间的间距
    QFN焊盘间距: 20 # 焊盘间距
    QFN焊盘边缘距离: -2  # QFN焊盘距离芯片边缘的距离
    QFN焊盘编号字体: Arial
    QFN焊盘编号字体大小: 10
    QFN_焊盘编号字体颜色: '#000000'
    QFN焊盘高度: 10 # 焊盘高度
    QFN焊盘宽度: 15 # 焊盘宽度
    QFN_焊盘图层: 2 # 焊盘图层
    QFN_焊盘圆角: 0.5 # 焊盘圆角
    QFN_焊盘颜色: '#cccccc'
    QFN_边线宽度: 0 # 焊盘边线宽度
    QFN_边线颜色: '#000000' # 焊盘边线颜色